// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using devhouse.Context;

#nullable disable

namespace devhouse.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260316164545_AddSeeds")]
    partial class AddSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Alice",
                            Lastname = "Johnson",
                            RoleId = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Bob",
                            Lastname = "Smith",
                            RoleId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Charlie",
                            Lastname = "Brown",
                            RoleId = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Diana",
                            Lastname = "Clark",
                            RoleId = 4,
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Frontend Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Backend Developer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fullstack Developer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Team Lead"
                        });
                });

            modelBuilder.Entity("Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Platform Team"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobile Team"
                        },
                        new
                        {
                            Id = 3,
                            Name = "API Team"
                        });
                });

            modelBuilder.Entity("devhouse.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTypeId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DevHouse Website",
                            ProjectTypeId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "DevHouse Mobile",
                            ProjectTypeId = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "DevHouse API",
                            ProjectTypeId = 3,
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("devhouse.Models.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Web Application"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobile App"
                        },
                        new
                        {
                            Id = 3,
                            Name = "API Service"
                        });
                });

            modelBuilder.Entity("Developer", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany("Developers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Team", "Team")
                        .WithMany("Developers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("devhouse.Models.Project", b =>
                {
                    b.HasOne("devhouse.Models.ProjectType", "ProjectType")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectType");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("Developers");
                });

            modelBuilder.Entity("Team", b =>
                {
                    b.Navigation("Developers");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("devhouse.Models.ProjectType", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
