// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using devhouse.Context;

#nullable disable

namespace devhouse.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("devhouse.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("TeamId");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Alice",
                            Lastname = "Johnson",
                            RoleId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Michael",
                            Lastname = "Cross",
                            RoleId = 2,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "elise@dev.com",
                            Firstname = "Elise",
                            Lastname = "Bergum",
                            Password = "AQAAAAIAAYagAAAAEIycYypww+L0YTgfBXysI/q12ZTOl6m2RO7SL3Q3OuEe2cOyBMw257v8+7MGOrMTQg==",
                            RoleId = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Bob",
                            Lastname = "Smith",
                            RoleId = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Firstname = "Marta",
                            Lastname = "Parks",
                            RoleId = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Firstname = "Diana",
                            Lastname = "Clark",
                            RoleId = 1,
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("devhouse.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTypeId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Website",
                            ProjectTypeId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobile",
                            ProjectTypeId = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "API",
                            ProjectTypeId = 3,
                            TeamId = 3
                        });
                });

            modelBuilder.Entity("devhouse.Models.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Web Application"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobile App"
                        },
                        new
                        {
                            Id = 3,
                            Name = "API Service"
                        });
                });

            modelBuilder.Entity("devhouse.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TeamLead"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("devhouse.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Platform"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 3,
                            Name = "API"
                        });
                });

            modelBuilder.Entity("devhouse.Models.Developer", b =>
                {
                    b.HasOne("devhouse.Models.Role", "Role")
                        .WithMany("Developers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("devhouse.Models.Team", "Team")
                        .WithMany("Developers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("devhouse.Models.Project", b =>
                {
                    b.HasOne("devhouse.Models.ProjectType", "ProjectType")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("devhouse.Models.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectType");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("devhouse.Models.ProjectType", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("devhouse.Models.Role", b =>
                {
                    b.Navigation("Developers");
                });

            modelBuilder.Entity("devhouse.Models.Team", b =>
                {
                    b.Navigation("Developers");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
